const SELECTOR = 'main[class*="practice-questions"]';
const GAP = 24;
const TEXT_WIDTH = 900;
const TEXT_PADDING = 48;
const RENDER_SCALE = 2;
const BACKGROUND = '#ffffff';

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  let task;

  if (message?.type === 'COPY_FULL_ASSIGNMENT') {
    task = createFullAssignment(message.tabId);
  } else if (message?.type === 'STACK_QUESTION_IMAGES') {
    task = stackQuestionImages(message.tabId);
  } else if (message?.type === 'FETCH_LECTURE_TRANSCRIPTS') {
    task = fetchLectureTranscripts(message.videos);
  } else {
    return;
  }

  task
    .then((result) => sendResponse({ ok: true, ...result }))
    .catch((error) => {
      console.error(error);
      sendResponse({ ok: false, error: error.message || 'Could not copy the questions.' });
    });

  return true;
});

async function fetchLectureTranscripts(videos) {
  const validVideos = (Array.isArray(videos) ? videos : [])
    .filter((video) => /^[A-Za-z0-9_-]{11}$/.test(video.videoId))
    .slice(0, 50);
  if (!validVideos.length) throw new Error('No valid YouTube videos were provided.');

  const apiKey = await getYouTubeApiKey(validVideos[0].videoId);
  const results = await Promise.allSettled(
    validVideos.map((video) => fetchEnglishTranscript(video, apiKey)),
  );
  const transcripts = results
    .filter((result) => result.status === 'fulfilled' && result.value)
    .map((result) => result.value);
  const skipped = results
    .map((result, index) => result.status === 'rejected' || !result.value
      ? validVideos[index].title
      : null)
    .filter(Boolean);

  if (!transcripts.length) {
    throw new Error('No uploaded or auto-generated English captions were available.');
  }

  const text = transcripts.map((transcript) => [
    transcript.title,
    transcript.link,
    '',
    transcript.text,
  ].join('\n')).join('\n\n---\n\n');

  return {
    text,
    copied: transcripts.length,
    total: validVideos.length,
    skipped,
  };
}

async function getYouTubeApiKey(videoId) {
  const response = await fetch(
    `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en`,
    { credentials: 'omit' },
  );
  if (!response.ok) throw new Error(`YouTube returned HTTP ${response.status}.`);

  const html = await response.text();
  const apiKey = html.match(/"INNERTUBE_API_KEY":"([^"]+)"/)?.[1];
  if (!apiKey) throw new Error('YouTube player configuration was unavailable.');
  return apiKey;
}

async function fetchEnglishTranscript(video, apiKey) {
  const clientVersion = '20.10.38';
  const playerUrl = new URL('https://www.youtube.com/youtubei/v1/player');
  playerUrl.searchParams.set('key', apiKey);
  playerUrl.searchParams.set('prettyPrint', 'false');

  const playerResponse = await fetch(playerUrl, {
    method: 'POST',
    credentials: 'omit',
    headers: {
      'content-type': 'application/json',
      'x-youtube-client-name': '3',
      'x-youtube-client-version': clientVersion,
    },
    body: JSON.stringify({
      context: {
        client: {
          clientName: 'ANDROID',
          clientVersion,
          androidSdkVersion: 30,
          osName: 'Android',
          osVersion: '11',
          hl: 'en',
          gl: 'US',
        },
      },
      videoId: video.videoId,
      contentCheckOk: true,
      racyCheckOk: true,
    }),
  });
  if (!playerResponse.ok) {
    throw new Error(`YouTube player request returned HTTP ${playerResponse.status}.`);
  }

  const player = await playerResponse.json();
  const tracks = player.captions
    ?.playerCaptionsTracklistRenderer
    ?.captionTracks || [];
  const isEnglish = (track) => {
    const language = track.languageCode?.toLowerCase();
    return language === 'en' || language?.startsWith('en-');
  };
  const track = tracks.find((candidate) => isEnglish(candidate) && candidate.kind !== 'asr')
    || tracks.find((candidate) => isEnglish(candidate) && candidate.kind === 'asr');
  if (!track?.baseUrl) return null;

  const captionUrl = new URL(track.baseUrl);
  captionUrl.searchParams.set('fmt', 'json3');
  const captionResponse = await fetch(captionUrl, { credentials: 'omit' });
  if (!captionResponse.ok) {
    throw new Error(`Caption request returned HTTP ${captionResponse.status}.`);
  }

  const body = await captionResponse.text();
  if (!body.trim()) throw new Error('YouTube returned an empty caption response.');
  const captions = JSON.parse(body);
  const lines = [];

  (captions.events || []).forEach((event) => {
    if (!Array.isArray(event.segs)) return;
    const line = event.segs
      .map((segment) => segment.utf8 || '')
      .join('')
      .replace(/\s+/g, ' ')
      .trim();
    if (line && lines.at(-1) !== line) lines.push(line);
  });

  if (!lines.length) return null;
  return {
    title: video.title || `Lecture ${video.videoId}`,
    link: `https://www.youtube.com/watch?v=${video.videoId}`,
    autoGenerated: track.kind === 'asr',
    text: lines.join('\n'),
  };
}

async function createFullAssignment(tabId) {
  if (!tabId) throw new Error('No active tab found.');
  const questions = await collectQuestions(tabId);

  if (!questions.length) {
    throw new Error('No questions were found on this page.');
  }

  const hasImages = questions.some((question) => question.urls.length);
  if (!hasImages) {
    const text = formatQuestionsAsText(questions);
    if (!text) throw new Error('No question text was found on this page.');
    return { format: 'text', text, copied: questions.length, total: questions.length };
  }

  const items = [];
  let loadedImageCount = 0;

  for (const [index, question] of questions.entries()) {
    const bitmaps = await fetchBitmaps(question.urls);
    loadedImageCount += bitmaps.length;

    const options = cleanOptions(question.options);
    if (question.text || options.length || bitmaps.length) {
      items.push({
        text: question.text,
        options,
        bitmaps,
        questionNumber: index + 1,
      });
    }
  }

  if (!loadedImageCount) {
    items.forEach((item) => item.bitmaps.forEach((bitmap) => bitmap.close()));
    throw new Error('The question images could not be loaded.');
  }

  const widestImage = Math.max(0, ...items
    .flatMap((item) => item.bitmaps.map((bitmap) => bitmap.width)));
  const logicalWidth = Math.max(TEXT_WIDTH, widestImage);
  const measureContext = new OffscreenCanvas(1, 1).getContext('2d');
  const layouts = items.map((item) => layoutQuestion(measureContext, item, logicalWidth));
  const logicalHeight = layouts.reduce((sum, layout) => sum + layout.height, 0)
    + GAP * (layouts.length - 1);
  const width = logicalWidth * RENDER_SCALE;
  const height = logicalHeight * RENDER_SCALE;

  const canvas = new OffscreenCanvas(width, height);
  const context = canvas.getContext('2d');
  context.scale(RENDER_SCALE, RENDER_SCALE);
  context.imageSmoothingEnabled = true;
  context.imageSmoothingQuality = 'high';
  context.fillStyle = BACKGROUND;
  context.fillRect(0, 0, logicalWidth, logicalHeight);

  let y = 0;
  layouts.forEach((layout, index) => {
    drawQuestion(context, layout, y, logicalWidth);
    y += layout.height;

    if (index < layouts.length - 1) {
      context.fillStyle = '#ececef';
      context.fillRect(0, y, logicalWidth, GAP);
      y += GAP;
    }
  });

  const blob = await canvas.convertToBlob({ type: 'image/png' });
  return {
    format: 'image',
    base64: toBase64(await blob.arrayBuffer()),
    copied: items.length,
    total: questions.length,
    images: loadedImageCount,
    width,
    height,
  };
}

async function stackQuestionImages(tabId) {
  if (!tabId) throw new Error('No active tab found.');

  const [{ result: urls }] = await chrome.scripting.executeScript({
    target: { tabId },
    func: (selector) => {
      const root = document.querySelector(selector);
      if (!root) return [];

      return [...root.querySelectorAll('img')]
        .map((image) => image.currentSrc || image.src || image.dataset.src
          || image.dataset.original)
        .filter(Boolean);
    },
    args: [SELECTOR],
  });

  if (!urls?.length) throw new Error('No question images were found on this page.');
  const bitmaps = await fetchBitmaps(urls);
  if (!bitmaps.length) throw new Error('The question images could not be loaded.');

  const logicalWidth = Math.max(...bitmaps.map((bitmap) => bitmap.width));
  const logicalHeight = bitmaps.reduce((sum, bitmap) => sum + bitmap.height, 0)
    + GAP * (bitmaps.length - 1);
  const width = logicalWidth * RENDER_SCALE;
  const height = logicalHeight * RENDER_SCALE;
  const canvas = new OffscreenCanvas(width, height);
  const context = canvas.getContext('2d');
  context.scale(RENDER_SCALE, RENDER_SCALE);
  context.imageSmoothingEnabled = true;
  context.imageSmoothingQuality = 'high';
  context.fillStyle = BACKGROUND;
  context.fillRect(0, 0, logicalWidth, logicalHeight);

  let y = 0;
  bitmaps.forEach((bitmap, index) => {
    const x = Math.round((logicalWidth - bitmap.width) / 2);
    context.drawImage(bitmap, x, y);
    y += bitmap.height;
    bitmap.close();

    if (index < bitmaps.length - 1) y += GAP;
  });

  const blob = await canvas.convertToBlob({ type: 'image/png' });
  return {
    format: 'image',
    base64: toBase64(await blob.arrayBuffer()),
    copied: bitmaps.length,
    total: urls.length,
    width,
    height,
  };
}

async function collectQuestions(tabId) {
  const [{ result }] = await chrome.scripting.executeScript({
    target: { tabId },
    func: (selector) => {
      const root = document.querySelector(selector);
      if (!root) return [];

      return [...root.querySelectorAll('section')]
        .filter((section) => {
          const content = section.querySelector('[class*="question-content"]');
          return content && content.closest('section') === section;
        })
        .map((section) => {
          const content = section.querySelector('[class*="question-content"]');
          const text = content?.innerText?.replace(/\s+/g, ' ').trim() || '';
          const options = [...section.querySelectorAll('label')]
            .map((label) => label.innerText.replace(/\s+/g, ' ').trim())
            .filter(Boolean);
          const urls = [...content.querySelectorAll('img')]
            .map((image) => image.currentSrc || image.src || image.dataset.src
              || image.dataset.original)
            .filter(Boolean);

          return { text, options, urls };
        })
        .filter((question) => question.text || question.options.length || question.urls.length);
    },
    args: [SELECTOR],
  });

  return result || [];
}

async function fetchBitmaps(urls) {
  const bitmaps = [];

  for (const url of urls) {
    try {
      const response = await fetch(url);
      if (!response.ok) throw new Error(`HTTP ${response.status}`);
      bitmaps.push(await createImageBitmap(await response.blob()));
    } catch (error) {
      console.warn('Skipped image', url, error);
    }
  }

  return bitmaps;
}

function cleanOptions(options) {
  return options.map((option) => option.replace(/^[A-Z][.)]\s*/i, '').trim()).filter(Boolean);
}

function formatQuestionsAsText(questions) {
  return questions.map((question, questionIndex) => {
    const options = cleanOptions(question.options);
    if (!question.text && !options.length) return null;

    const lines = [`${questionIndex + 1}. ${question.text}`.trim()];
    options.forEach((option, optionIndex) => {
      lines.push(`${String.fromCharCode(65 + optionIndex)}. ${option}`);
    });
    return lines.join('\n');
  }).filter(Boolean).join('\n\n');
}

function layoutQuestion(context, item, width) {
  const contentWidth = width - TEXT_PADDING * 2;
  context.font = '600 25px sans-serif';
  const questionLines = wrapText(
    context,
    `${item.questionNumber}. ${item.text}`.trim(),
    contentWidth,
  );

  context.font = '22px sans-serif';
  const optionLines = item.options.flatMap((option, optionIndex) =>
    wrapText(
      context,
      `${String.fromCharCode(65 + optionIndex)}. ${option}`,
      contentWidth - 24,
    ));
  const imagesHeight = item.bitmaps.reduce((sum, bitmap) => sum + bitmap.height, 0)
    + Math.max(0, item.bitmaps.length - 1) * 12;

  return {
    ...item,
    questionLines,
    optionLines,
    height: TEXT_PADDING * 2
      + questionLines.length * 35
      + (item.bitmaps.length ? 18 + imagesHeight : 0)
      + (optionLines.length ? 18 + optionLines.length * 31 : 0),
  };
}

function drawQuestion(context, layout, y, width) {
  context.fillStyle = '#ffffff';
  context.fillRect(0, y, width, layout.height);

  let lineY = y + TEXT_PADDING;
  context.fillStyle = '#17171a';
  context.font = '600 25px sans-serif';
  context.textBaseline = 'top';
  layout.questionLines.forEach((line) => {
    context.fillText(line, TEXT_PADDING, lineY);
    lineY += 35;
  });

  if (layout.bitmaps.length) {
    lineY += 18;
    layout.bitmaps.forEach((bitmap, index) => {
      context.drawImage(bitmap, Math.round((width - bitmap.width) / 2), lineY);
      lineY += bitmap.height;
      if (index < layout.bitmaps.length - 1) lineY += 12;
      bitmap.close();
    });
  }

  if (layout.optionLines.length) lineY += 18;
  context.fillStyle = '#34343a';
  context.font = '22px sans-serif';
  layout.optionLines.forEach((line) => {
    context.fillText(line, TEXT_PADDING + 24, lineY);
    lineY += 31;
  });
}

function wrapText(context, text, maxWidth) {
  const words = text.split(/\s+/).filter(Boolean);
  const lines = [];
  let line = '';

  words.forEach((word) => {
    const candidate = line ? `${line} ${word}` : word;
    if (line && context.measureText(candidate).width > maxWidth) {
      lines.push(line);
      line = word;
    } else {
      line = candidate;
    }
  });

  if (line) lines.push(line);
  return lines.length ? lines : [''];
}

function toBase64(buffer) {
  const bytes = new Uint8Array(buffer);
  const chunkSize = 0x8000;
  let output = '';

  for (let index = 0; index < bytes.length; index += chunkSize) {
    output += String.fromCharCode.apply(null, bytes.subarray(index, index + chunkSize));
  }

  return btoa(output);
}
